baseURL = "https://jiaxuyang.github.io/blog/"
languageCode = "zh-cn"
title = "Xuyang's Blog"
# theme = "ananke"
theme = "hugo-octopress"
# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 6

[permalinks]
# Configures post URLs
post = "/blog/:year-:month-:day-:title/"

[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -10
[[menu.main]]
  Name = "Tags"
  URL = "/tags/"
  weight = -5
[[menu.main]]
  Name = "Categories"
  URL = "/categories/"

[[menu.sidebar]]
  Name = "golang"
  URL = "/golang/"
  weight = 0
[[menu.sidebar]]
  Name = "multilingual"
  URL = "/multilingual/"
  weight = 1
[[menu.sidebar]]
  Name = "misc"
  URL = "/misc/"
  weight = 1

[params]
  mainSections = ["golang", "multilingual", "misc"]
  generateTaxonomyList = true
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Collections"
  tableOfContents = true
#   sidebarHeader = "Sidebar Header"
#   sidebarText = """Here's a [link to google](https://www.google.com)
# </br>
# Second line
# </br>
# Third line
# This line has two spaces in the end to create a new line using markdown[two spaces here]  
# Forth line
# """
  sidebarRecentLimit = 5
  github = "https://github.com/jiaxuyang/"
  bitbucket = ""
  gitlab = ""
  twitter = ""
  keybase = ""
  linkedin = ""
  stackoverflow = ""
  googleplus = ""
  youtube = ""
  facebook = ""
  instagram = ""
  bitcoin = ""

  # If false, all contents of posts will appear on the front page and in pagination
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Xuyang"

  # This text appears in site header under website title
  subtitle = "“Get busy living or get busy dying.” — Andy Dufresne"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Would you like to know more? &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = ""

  # Populate with your search keywords - these will appear in meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or set to false to use local fonts
  remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise, the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or is set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  compactIndex = true